import React from 'react';
import Header from '../components/Header';
import Head from 'next/head';
import Banner from '../components/Banner';
import SmallCard from '../components/SmallCard';
import MediumCard from '../components/ MediumCard';
import LargeCard from '../components/LargeCard';
import Footer from '../components/Footer';
export default function Home({ exploreData, cardsData }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Banner/>

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
         <section>
            <h2 className='text-4xl font-semibold p-5'> Explore NearBy </h2>
            {/* PUll endpoints from api */}
            <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {exploreData?.map(({ img, location, distance }) => (
               <SmallCard
                key={img}
                img={img}
                distance={distance}
                location={location} />
             ))} 
            </div>
         </section>

         <section>
             <h2 className='text-4xl font-semibold py-8'> Live Any Where</h2>
             <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
             {cardsData?.map(({img, title}) => (
                <MediumCard key={img} img={img} title={title} />
             ))}
              </div>
         </section>

         <LargeCard
           img="https://links.papareact.com/4cj"
           title="The Greatest OutDoors"
           description="Wishlists curated by event house"
           buttonText="Get Inspired"
         />
      </main>
      <Footer/>
    </div>
  )
}

export async function getStaticProps(){
    const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G').
    then((res) => res.json());

    const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT").
    then((res) => res.json())
    return{
      props:{
        exploreData,
        cardsData
      }
    }
}
